development:
  merchant_id: "{84BE7E7F-698A-6C74-F820-AE359C2A07C2}"
  braspag_url: "https://homologacao.pagador.com.br"

test:
  merchant_id: "{84BE7E7F-698A-6C74-F820-AE359C2A07C2}"
  braspag_url: "https://homologacao.pagador.com.br"

